trigger: none

pool: Default

stages:
- stage: A
  displayName: stage1
  pool: Default
  jobs: 
  - job: A
    displayName: Terraform init
    steps: 
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'svn'
        backendAzureRmResourceGroupName: 'backend-rg'
        backendAzureRmStorageAccountName: 'backendstgaviinash'
        backendAzureRmContainerName: 'terraform-backend'
        backendAzureRmKey: 'prod.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'svn'

