name: Terraform Deployment-$(Build.SourceBranchName)-$(Build.BuildId)

trigger:
  branches:
    include:
      - main
    exclude:
      - dev
  paths:
    exclude:
      - '**/*.md'
      - '**/*.txt'

pool: Default

stages:
- stage: A
  displayName: stage1
  pool: Default
  jobs: 
  - job: Terraform
    steps:
    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'SVB'
        backendAzureRmResourceGroupName: 'backend-rg'
        backendAzureRmStorageAccountName: 'backendstgaviinash'
        backendAzureRmContainerName: 'terraform-backend'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTaskV4@4
      displayName: Terraform plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'SVB'
