name: Terraform Deployment-$(Build.SourceBranchName)-$(Build.BuildId)

trigger:
  branches:
    include:
      - main
    exclude:
      - dev
  paths:
    exclude:
      - '**/*.md'
      - '**/*.txt'
pool: Default

variables:
  - group: INFRACOST_API_KEY
    
stages:
- stage: Validate
  displayName: 'Validate and Security Scan'
  pool: Default
  jobs: 
  - job: Terraform
    steps:
    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'SVB'
        backendAzureRmResourceGroupName: 'backend-rg'
        backendAzureRmStorageAccountName: 'backendstgaviinash'
        backendAzureRmContainerName: 'terraform-backend'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTaskV4@4
      displayName: Terraform plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'SVB'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Invoke-WebRequest https://github.com/infracost/infracost/releases/latest/download/infracost-windows-amd64.tar.gz -OutFile infracost.tar.gz
          tar -xvf infracost.tar.gz
          .\infracost.exe --version
          $env:INFRACOST_API_KEY = "$(Infracostapitoken)"
          .\infracost.exe breakdown --path '$(System.DefaultWorkingDirectory)' --format table

       